import Image from "next/image";
import { site } from "@/lib/site";

/**
 * The official wordmark ships as white glyphs on transparency, so light mode
 * gets the navy recolour generated by scripts/make-brand-assets.py. Both are
 * rendered and CSS picks the right one, which keeps the swap instant.
 */
export function Logo({ className = "h-9 w-auto", priority = false }: { className?: string; priority?: boolean }) {
  return (
    <span className="inline-flex">
      <Image
        src="/brand/logo-wordmark.png"
        alt={site.name}
        width={2341}
        height={511}
        priority={priority}
        className={`logo-dark-only ${className}`}
      />
      <Image
        src="/brand/logo-wordmark-dark.png"
        alt=""
        aria-hidden="true"
        width={2341}
        height={511}
        priority={priority}
        className={`logo-light-only ${className}`}
      />
    </span>
  );
}
